(load "~/code/advent-of-code/src/2024/helpers.lisp")

(defparameter directions '(
(-1 -1) (-1 0) (-1 1)
 (0 -1)         (0 1)
 (1 -1)  (1 0)  (1 1)))

(defparameter xmas "XMAS")

(defun part1 (text)
    (let* ((sum 0)
           (dimensions (array-dimensions text))
           (len (first dimensions))
           (width (second dimensions)))
        (dotimes (x len)
            (dotimes (y width)
                (dolist (dir directions)
                        (let ((new-x (+ x (first dir)))
                              (new-y (+ y (second dir)))
                              (word (make-array 1
                                        :element-type 'character 
                                        :adjustable t 
                                        :fill-pointer 1 
                                        :initial-contents (list (aref text x y)))))
                        (dotimes (iter 3)
                            (unless (or (> 0 new-x)
                                        (> 0 new-y)
                                        (< (- len 1) new-x)
                                        (< (- len 1) new-y))
                                (vector-push-extend (aref text new-x new-y) word)
                                (when debug-mode (format t "Value at new index ~A x ~A, walking from ~A x ~A: ~A [~A]~%" new-x new-y x y (aref text new-x new-y) word))
                                (incf new-x (first dir))
                                (incf new-y (second dir))))
                        (when (string= xmas word) (incf sum)))))
            (when debug-mode (fresh-line)))
        sum))

(defun part2 (text)
    (let* ((sum 0)
           (dimensions (array-dimensions text))
           (len (first dimensions))
           (width (second dimensions)))
        (dotimes (x len)
            (dotimes (y width)
                (let ((cur (aref text x y))
                      (nw (ignore-errors (aref text (1- x) (1- y))))
                      (ne (ignore-errors (aref text (1- x) (1+ y))))
                      (sw (ignore-errors (aref text (1+ x) (1- y))))
                      (se (ignore-errors (aref text (1+ x) (1+ y)))))
                    (when (and (char= cur #\A)
                               (and (characterp nw) (characterp ne) (characterp sw) (characterp se))
                               (or (and (char= nw #\M) (char= se #\S)) 
                                   (and (char= nw #\S) (char= se #\M)))
                               (or (and (char= ne #\M) (char= sw #\S))
                                   (and (char= ne #\S) (char= sw #\M)))) 
                          (incf sum)))))
        sum))

(defparameter debug-mode nil)
(equal 2718 (part1 (get-puzzle-input 2024 04 :2d-array)))
(equal 2046 (part2 (get-puzzle-input 2024 04 :2d-array)))
